version: '3.9'

services:
   db:
    container_name: db
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sr_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}