-- AlterTable
ALTER TABLE "Addon" ALTER COLUMN "expiryDate" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Delivery" ALTER COLUMN "scheduledFor" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Patron" ALTER COLUMN "joiningDate" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "expiryDate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "lastIssued" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "lastReturned" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "oldExpiry" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "newExpiry" SET DATA TYPE TIMESTAMP(3);
